### ISSUE TITLE
CommonsChunkPlugin

### ISSUE THREAD

**Issue by kennethaa** [trivago/parallel-webpack#1]
Hi,

Today my webpack config has around 10 entries and I use the CommonsChunkPlugin to generate a common.js file. Is it possible to use CommonsChunkPlugin with parallel-webpack? 

Do I have to change my webpack config from a object with many entries to an array like you do in your example?

Best regards,
Kenneth

**Comment by pago** [comment]
Hi, that's a pretty good question. I was about to say "sure" because we use both of them together but our use case is most probably slightly different than yours.
For our setup, we actually create the same bundles but process them differently (i.e. drop touch/gesture detection when dealing with IE8, include a few fixes for certain platforms, etc.) but that means we need a different common chunk for every one of our build targets.
What you'll most likely want to have, instead, is a common bundle that is automatically generated and shared between your entry points while parallelizing the build of the entry points.
And because when using parallel-webpack those run independently from each other in separate processes, they can't share the same cache and can't actually share the information of what should go into the common chunk.

If you're using it as specified in the webpack documentation ( http://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code ), so use it for explicitly specified chunks, then it should work just fine and you could most probably even create the common chunk in parallel to your actual app entry points.

Please give it a try and let me know if it works for you. If not, I'll see what I can do to help.

Regardless of that, parallel-webpack currently only processes the array you return from the webpack.config.js so for it to be able to parallelize things, you need to return an array. It would be feasible to automatically convert a single config by extracting the entry points and doing some minor transform (i.e. automatically splitting the configs based on the entry points) but we don't have that feature yet and depending on the particular use case it might actually be better to have multiple entry points in the same build. i.e. our build targets all have around 5 entry points which are processed sequentially by webpack, taking advantage of the Webpack cache.
The most efficient setup really depends on how many cores you have available, how fast those cores are and how much memory you have available.

I hope that answers your question. If not, please let me know how I can assist.

**Comment by kennethaa** [comment]
Thank you for a very good answer. I will give it a try in the next days and write back here.

**Comment by pago** [comment]
I'll close this one for the time being. Please feel free to reopen if you have any further questions.

**Comment by kennethaa** [comment]
Yes, could be that I go back and test parallel-webpack later when we get more entries (> 50).
