### ISSUE TITLE
Using a config object directly instead of configPath?

### ISSUE THREAD

**Issue by kmck** [trivago/parallel-webpack#11]
Is this built in such a way that you can only supply a path to a Webpack config file and not an object containing the configuration? Glancing at the code, it seems that way, but I wanted to ask in case I was missing something. Thanks!

**Comment by pago** [comment]
Correct. The reason for that is that a webpack config can consist of object instances which can't be easily serialized using `JSON.stringify` which we need to do in order to pass it to the worker (a child process). Thus, the only thing we can do is pass in the path to the configuration file and load it within that child process and then select the correct configuration based on its index for that particular worker.

There's a shortcut in the code so that if there is only one configuration, it'll pass that config directly to webpack, skipping the child process entirely.

**Comment by kmck** [comment]
Thanks for the explanation, and darn. :smile:
