### ISSUE TITLE
[Question] Does it work with webpack dev server or middleware ?

### ISSUE THREAD

**Issue by gcazaciuc** [trivago/parallel-webpack#18]
In dev mode, webpack dev server or webpack dev middleware delivers great performance by not writing assets to disk. However, it would be awesome if it would also compile the entry points in parallel(I have about 3 of them). Does parallel-webpack work with these 2 ? Could it be made to work with them if not ?

**Comment by pago** [comment]
Short answer: Not sure.
In general, parallel-webpack does not parallelise entry points but only webpack configurations. So even if it did work, it wouldn't do what you'd like it to do.

In our use case, we have made our webpack configuration configurable through command line parameters so that we only generated one config when using the dev server. Thus we don't need parallel-webpack for the development process. We also have flags to disable/enable some entry points that are rarely touched during development.

Perhaps something like that would work for you as well?
