### ISSUE TITLE
[Question] Does this work with Webpack 2?

### ISSUE THREAD

**Issue by phaistonian** [trivago/parallel-webpack#19]
What the title says :)

**Comment by pago** [comment]
In theory it should work but I haven't tested it yet. Perhaps you could give it a test run and let us know if it does?

In general it is our goal to support Webpack 2. So if there are problems, you can be sure that we'll fix them.

**Comment by phaistonian** [comment]
Will do and report any findings.

Thank you.

**Comment by TheLarkInn** [comment]
I have been able to run this successfully on a few webpack v2 builds. I have a OSS plugin thats a work in progress, that has a `npm run build:examples` command and exports an array of configs. I will try and run paralell-webpack there and see if it works.

**Comment by phaistonian** [comment]
The first (and blocking issue) for me is that when I set the output to be `filename: '[name].[chunkhash].js',` I get this LITERALLY.

The bundled files are named   '[name].[chunkhash].js'.

I have no idea if this is a webpack 2 thing or not, but it's blocking me moving on with it:)

**Comment by phaistonian** [comment]
Apparently I was wrong - or so I am told by our IT team.

Will re-check and get back to you.

**Comment by phaistonian** [comment]
Turns it works - sort of.

The issue is that the css (using stylus loader) is not uglified or minified.

As if the `-p` is ignored.

**Comment by pago** [comment]
Did you take a look at this: https://webpack.js.org/how-to/upgrade-from-webpack-1/#uglifyjsplugin-minimize-loaders ?

**Comment by phaistonian** [comment]
@pago yes. I have been using Webpack 2 since the early days :)

**Comment by pago** [comment]
@phaistonian 
Turns out we don't pass any command line arguments to webpack as we're using the node.js API and would have to implement the behaviour of those flags within `parallel-webpack`. That'd eventually result in different behaviour of the flags when switching between `parallel-webpack` and `webpack`, which I'd like to avoid.

So you'd need to activate minification within the config itself. Could you give that a try? Should work.

Most interesting question now seems to be whether we should detect some commonly used flags (such as `-p`) which won't work and warn about their usage or if we should actually implement them.

**Comment by phaistonian** [comment]
@pago That makes sense.

I will give it a try and get back to you.

Thank you.

**Comment by rkrambovitis** [comment]
Manually using cssnano in postcss works fine.

Thx :)

**Comment by aniddan** [comment]
How about you'll leave Webpack as a peer dependency and then user could choose which version to use?

**Comment by pago** [comment]
It should already pick local webpack installations over the one included with it. That's just convenience so that you don't necessarily have to install both, `parallel-webpack` and `webpack`. The one installed with the project you're running `parallel-webpack` on has priority though.

**Comment by pago** [comment]
I'll close this one for now. Please feel free to create a new ticket if any problems with Webpack 2 show up.
