### ISSUE TITLE
Multi-Variant CommonChunks

### ISSUE THREAD

**Issue by Lukx** [trivago/parallel-webpack#5]
Although #1 is closed, I might believe there is a follow-up use case for a "common" chunk across *all* variants. So: When a given module is the same in *all* variants, it gets extracted to a "common" chunk. Opposed to that, the current behaviour creates one "common" chunk for each variant, dropping potential re-use of chunks across multivariant environments quite a bit.

Think of our trivago use case: A user on trivago.ae switching from the LTR to the RTL layout of that page would have to re-download *each* of the chunks, although only relatively little may actually be altered.

And no: I have not the slightest idea how to achieve this given the current code.

**Comment by pago** [comment]
I believe that's some very specific use case on our side and I also believe you've already given about 95% of the solution I intend to target. ;)

Let's examine what you want by looking at some simple example:

Variant A: M1, A2, M3
Variant B: M1, B2, M3

Now you'd like to have a "common chunk" consisting of (M1, M3) and the two variants which consist of (A2) and (B2). So:
Common Chunk: M1, M3
Variant A: A2
Variant B: B2

I can think of two ways to do that:

1) Parse the generated output to extract identical ones and somehow replace them with a common chunk entry.
2) Identify whether or not the modules content will be changed as part of the variant. If it is, replace its content with a usage of its definition within the common chunk/dll. If its not, adjust the content according to the variant definition and replace the original content with that. Obviously, when generating the common chunk, that'd logic would be pretty much reversed.

The benefit of option 2 is that it'll be a separate plugin/loader and would not require an adjustment to either webpack or parallel-webpack. Due to being executed in parallel, the usage might not even incur a significant time penalty.
But maybe @sokra has some better idea?

**Comment by sokra** [comment]
Even when this is be technically possible, I wouldn't recommend doing this "optimization". This decreases performance for users that only request a single variant, in trade to better performance for users that request multiple variants (by switching between variants). In my optinion much more users request only a single variant, so you should better optimize for this use case.

---

The CommonsChunksPlugin cannot be used with multiple compilations. This use case is only possible with the DllPlugin. But this means you need to choose the common modules manually. Before trying to accomplish this is parallel-webpack, you should try it with plain webpack, because this is difficult enough...

**Comment by pago** [comment]
@sokra Thank you for your feedback. You're right that in this particular use case having a common chunk would not make much sense. The more I think about it, the more I have to agree with you. Very good point indeed.

The only thing I can think of that we might still want to consider is the use case I've seen as most common for parallel-webpack so far: Projects with a large amount of entry points where building those entry points in parallel might help to speed things up (probably because the entry points share only a low percentage of modules so that the caching is not as efficient as the parallelisation would be).

Switching from webpack to parallel-webpack in those cases would then yield a build performance benefit while also destroying the chance of using the CommonChunks plugin. Sure, you can use the DllPlugin instead, but that'd then remove the possibility to auto-discover/decide the content of the common chunk as you've correctly described.

If we accept that as a valid use case (instead of mentioning that a project probably shouldn't even have so many entry points), then I believe the question of supporting the CommonChunksPlugin should also be considered valid as it generally would have a positive impact on all users of an application.
It's not a use case that is relevant for us but I've seen a few cases where this was how people wanted to use parallel-webpack so I tend to think we might at least consider if/how we can support it or want to invest some time into a "Best practices" documentation that explains why so many entry points aren't a good idea.

Trouble is that the only solutions I can come up with require either pre- or post-processing, both of which might be quite expensive and thus have the potential to defeat the purpose. They're also outside of the scope of parallel-webpack with regards to the implementation and all we could really do here would be to offer hooks which allow such usages.

But, like I said: I'm not entirely certain that it is a valid use case and you're quite right about the variants part not being a valid use case either. The solution would be complicated, the DllPlugin can be used as a workaround and so on.
