### ISSUE TITLE
Multiple function configuration support

### ISSUE THREAD

**Issue by fakalit** [trivago/parallel-webpack#58]
right now it's not possible to use parallel-webpack with multiple function configuration,
(https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations)
which you now need to use to pass command line arguments to webpack.
(https://github.com/webpack/webpack/issues/2254#issuecomment-280470290).

current behavior is throwing of Unhandled rejection TypeError.

**Comment by efegurkan** [comment]
Hello @fakalit,

Thank you for reporting issue :)

You can export one function returning multiple configurations. It should work as expected. 
I am not sure if you are mentioning multiple functions inside configuration array? If that is the case i personally don't see a point since you cannot send different env options to different arrays via command line flags. In the end that would be the same with a function returning configuration array.

If there is something else, that would be awesome if you can provide a dummy repository. 

Cheers,

**Comment by fakalit** [comment]
yes, one function returning multiple configuration works and it covers the use case. I thought I tried that but apparently, I didn't. though I think you might still want to support multiple function configuration at some point as a convenience feature because it's a format supported by webpack now.
